services:
  - type: web
    name: korea-week-qr-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn generate_qr_codes:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
